### ISSUE TITLE
Czwarta praca domowa - Ahmed Abdelkarim, Aleksandra Hernik, Iwona Żochowska

### ISSUE THREAD

**Issue by Alkuerissa** [pbiecek/TechnikiWizualizacjiDanych2017#100]
Zgodnie z poprzednią dyskusją prosimy o ocenienie naszej zapomnianej pracy domowej :)

**Comment by pbiecek** [comment]
Pomysł na nalizę ciekawy i przeprowadzenie też, ale obawiam się że w testowane wykresy wkrył się problem, który poważnie rzutuje na wynikach.
Głównie chodzi o określenie jedyna/pierwsza/druga, którego zrozumienei jest niezbędne aby jakkolwiek podejść do zrozumienia wykresów. Niesteyty to zastosowane nazewnictwo z niczym się nei kojarzy i powoduje że wykresy trudniej odczytać. Na wykresie z mapą ciepła opisy osi wyglądają na zamienione. 
Wykresu 'ocena czytelności nie potrafię odczytać'. Czy słupki to średnia?
Zaprezentowany wynik dotyczący błędów w wartościach procentowy jest nieprawdopodobny. Heatmapa o najmniejszym błędzie w odczytywanych wartościach? To nie możliwe.
