### ISSUE TITLE
PD_07, PD_08 - Artur Minorczyk

### ISSUE THREAD

**Issue by minorczyka** [pbiecek/TechnikiWizualizacjiDanych2017#148]
Pull request "PD_07, PD_08 - Artur Minorczyk" zawierał dwie prace domowe 7 i 8. Oceniona natomiast została jedynie praca 8.

**Comment by pbiecek** [comment]
Praca wykonana estetycznie. Od strony technicznej wszystko ok.
Ale mało interakcji, poza tym tego rodzaju dane można przedstawić znacznie lepiej niż słupkami.
Najlepszym przykładem są wykresy zmian używane np. do zaznaczania przebiegów wyścigów Formuły 1
http://i.imgur.com/3YE3YnI.jpg?1
Gdyby taki wykres był tworzony dla tych danych wyglądałby znacznie lepiej
