### ISSUE TITLE
Wyniki projektu 2 + punktacja przedmiotu

### ISSUE THREAD

**Issue by franiis** [pbiecek/TechnikiWizualizacjiDanych2017#206]
Dzień dobry,
Chciałbym poprosić Pana o umieszczenie wyników Projektu 2 z Technik Wizualizacji Danych oraz o umieszczenie punktacji całego przedmiotu na stronie (lub w innym dostępnym miejscu). 
Umieszczenie tych informacji omawialiśmy na ostatnim wykładzie (10.01.18r.).

Pozdrawiam,
Piotr Krzeszewski

**Comment by pbiecek** [comment]
Obie rzeczy są już na stronie, razem z punktami za prezentacje.
(bez względu na to jaka ocena wychodzi, proszę nie ,,pomijać'' trzeciego projektu)
