### ISSUE TITLE
Projekt 2

### ISSUE THREAD

**Issue by ppollakr** [pbiecek/TechnikiWizualizacjiDanych2017#219]
Zgodnie z ustaleniami z rozmowy wstawiam issue przypominające o dokładniejszym przeanalizowaniu drugiego projektu P. Pollak i K. Szczawiński

**Comment by pbiecek** [comment]
Punkty i oceny są już na sieci. W panów przypadku nawet dodanie kilkunastu punktów za ten projekt nie zmieni oceny końcowej. Jeżeli mimo wszystko chcą Panowie porozmawiać to oczywiście zapraszam.
