### ISSUE TITLE
Pomieszane oceny prac domowych

### ISSUE THREAD

**Issue by komosinskid** [pbiecek/TechnikiWizualizacjiDanych2017#221]
W pracy domowej o tablo która była jako pd09 wstawił mi Pan punkty do pd10, a do choinki już chyba Pan zapomniał. W każdym razie powinienem mieć punkty zarówno w pd09 jak i w pd10, ponieważ wysłałem i choinkę i tablo.

**Comment by pbiecek** [comment]
poprawione
