### ISSUE TITLE
Zadanie domowe - tydzień 4

### ISSUE THREAD

**Issue by SimplifyAll** [pbiecek/TechnikiWizualizacjiDanych2017#66]
Dzień dobry,

Z racji Wszystkich Świętych termin projektu jest przesunięty o tydzień.
Chciałbym się jednak upewnić czy termin nadesłania zadania domowego (badanie) również jest przesunięty o tydzień?

**Comment by pbiecek** [comment]
Tak, to dobry pomysł, czas na badanie jest do naszych kolejnych zajęć
